# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    annotations: false
    http_method_override: false
    handle_all_throwables: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax

    # Enable CSRF protection
    csrf_protection: true

    #esi: true
    #fragments: true
    php_errors:
        log: true
    
    # Rate limiting configuration
    rate_limiter:
        registration:
            policy: 'sliding_window'
            limit: 3
            interval: '15 minutes'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
