name: Claude – Implement Story

on:
  issues:
    types: [labeled]
    # run only when specific label is added

jobs:
  implement-story:
    if: contains(github.event.label.name, 'Story ready')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Claude – implement story
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPO_URL: ${{ github.server_url }}/${{ github.repository }}
          MODE: write
          PROMPT: ${{ github.event.issue.body }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          CLAUDE_CREDENTIALS_B64: ${{ secrets.CLAUDE_CREDENTIALS_BASE64 }}
          ONLY_AUTOMATE_OWN_ISSUES: 1
        run: |
          docker run --rm \
            -e GH_TOKEN \
            -e REPO_URL \
            -e MODE \
            -e PROMPT \
            -e ISSUE_NUMBER \
            -e CLAUDE_CREDENTIALS_B64 \
            -e ONLY_AUTOMATE_OWN_ISSUES \
            ghcr.io/dpeuscher/claude-code-agent:latest 