name: Claude – Apply Feedback

on:
  pull_request_review_comment:
    types: [created]
  issue_comment:
    types: [created]

jobs:
  apply-feedback:
    if: github.event.pull_request || (github.event.issue.pull_request && github.event.comment)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Claude – apply PR feedback
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPO_URL: ${{ github.server_url }}/${{ github.repository }}
          MODE: apply_feedback
          PROMPT: ${{ github.event.comment.body }}
          PR_NUMBER: ${{ github.event.pull_request.number || github.event.issue.number }}
          CLAUDE_CREDENTIALS_B64: ${{ secrets.CLAUDE_CREDENTIALS_BASE64 }}
          ONLY_AUTOMATE_OWN_ISSUES: 1
        run: |
          docker run --rm \
            -e GH_TOKEN \
            -e REPO_URL \
            -e MODE \
            -e PROMPT \
            -e PR_NUMBER \
            -e CLAUDE_CREDENTIALS_B64 \
            -e ONLY_AUTOMATE_OWN_ISSUES \
            ghcr.io/dpeuscher/claude-code-agent:latest 