name: Claude – Detail Story

on:
  issues:
    types: [opened]
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'Target issue number (required for manual run)'
        required: true
        type: string

jobs:
  generate-detail:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Claude – create detailed user story
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPO_URL: ${{ github.server_url }}/${{ github.repository }}
          MODE: detail
          PROMPT: ${{ github.event.issue.body || github.event.inputs.issue_number && 'Manual detail trigger' }}
          ISSUE_NUMBER: ${{ github.event.issue.number || inputs.issue_number }}
          CLAUDE_CREDENTIALS_B64: ${{ secrets.CLAUDE_CREDENTIALS_B64 }}
          ONLY_AUTOMATE_OWN_ISSUES: 1
        run: |
          docker run --rm \
            -e GH_TOKEN \
            -e REPO_URL \
            -e MODE \
            -e PROMPT \
            -e ISSUE_NUMBER \
            -e CLAUDE_CREDENTIALS_B64 \
            -e ONLY_AUTOMATE_OWN_ISSUES \
            ghcr.io/dpeuscher/claude-code-agent:latest 
