name: Claude – Detail Story

on:
  issues:
    types: [opened, labeled, unlabeled]
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'Target issue number (required for manual run)'
        required: true
        type: string

concurrency:
  group: claude-detail-${{ github.event.issue.number || github.event.inputs.issue_number }}
  cancel-in-progress: true

jobs:
  generate-detail-github:
    # Run on new issues OR when AI label is present but Story Ready is not
    if: ${{ startsWith(github.server_url, 'https://github.com') && (github.event.action == 'opened' || ((github.event.action == 'labeled' || github.event.action == 'unlabeled') && contains(github.event.issue.labels.*.name, 'AI') && !contains(github.event.issue.labels.*.name, 'Story Ready'))) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Claude – create detailed user story (GitHub)
        env:
          CI_PROVIDER: github
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPO_URL: ${{ github.server_url }}/${{ github.repository }}
          MODE: detail
          PROMPT: ${{ github.event.issue.body || github.event.inputs.issue_number && 'Manual detail trigger' }}
          ISSUE_NUMBER: ${{ github.event.issue.number || inputs.issue_number }}
          CLAUDE_CREDENTIALS_B64: ${{ secrets.CLAUDE_CREDENTIALS_B64 }}
          ONLY_AUTOMATE_OWN_ISSUES: 1
        run: |
          docker run --rm \
            -e CI_PROVIDER \
            -e GH_TOKEN \
            -e REPO_URL \
            -e MODE \
            -e PROMPT \
            -e ISSUE_NUMBER \
            -e CLAUDE_CREDENTIALS_B64 \
            -e ONLY_AUTOMATE_OWN_ISSUES \
            ghcr.io/dpeuscher/claude-code-agent:latest

  generate-detail-forgejo:
    # Run on new issues OR when AI label is present but Story Ready is not
    if: ${{ !startsWith(github.server_url, 'https://github.com') && (github.event.action == 'opened' || ((github.event.action == 'labeled' || github.event.action == 'unlabeled') && contains(github.event.issue.labels.*.name, 'AI') && !contains(github.event.issue.labels.*.name, 'Story Ready'))) }}
    runs-on: docker
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Claude – create detailed user story (Forgejo)
        env:
          CI_PROVIDER: forgejo
          FORGEJO_TOKEN: ${{ secrets.FORGEJO_TOKEN }}
          FORGEJO_BASE_URL: ${{ secrets.FORGEJO_BASE_URL }}
          REPO_URL: ${{ github.server_url }}/${{ github.repository }}
          MODE: detail
          PROMPT: ${{ github.event.issue.body || github.event.inputs.issue_number && 'Manual detail trigger' }}
          ISSUE_NUMBER: ${{ github.event.issue.number || inputs.issue_number }}
          CLAUDE_CREDENTIALS_B64: ${{ secrets.CLAUDE_CREDENTIALS_B64 }}
          ONLY_AUTOMATE_OWN_ISSUES: 1
        run: |
          docker run --rm \
            -e CI_PROVIDER \
            -e FORGEJO_TOKEN \
            -e FORGEJO_BASE_URL \
            -e REPO_URL \
            -e MODE \
            -e PROMPT \
            -e ISSUE_NUMBER \
            -e CLAUDE_CREDENTIALS_B64 \
            -e ONLY_AUTOMATE_OWN_ISSUES \
            ghcr.io/dpeuscher/claude-code-agent:latest
