# TEMPLATE – Enable in consumer repo only
name: Claude – PR Review

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Target PR number (for manual run)'
        required: false
        type: string

concurrency:
  group: claude-review-${{ github.event.pull_request.number || github.event.inputs.pr_number }}
  cancel-in-progress: true

jobs:
  review-pr:
    if: github.event.action != 'labeled' || contains(github.event.label.name, 'AI')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Claude – review PR
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPO_URL: ${{ github.server_url }}/${{ github.repository }}
          MODE: review
          PROMPT: "Automated PR review"
          PR_NUMBER: ${{ github.event.pull_request.number || inputs.pr_number }}
          CLAUDE_CREDENTIALS_B64: ${{ secrets.CLAUDE_CREDENTIALS_B64 }}
        run: |
          docker run --rm \
            -e GH_TOKEN \
            -e REPO_URL \
            -e MODE \
            -e PROMPT \
            -e PR_NUMBER \
            -e CLAUDE_CREDENTIALS_B64 \
            ghcr.io/dpeuscher/claude-code-agent:latest 