name: Claude Issue Handler

on:
  issues:
    types: [opened]
  workflow_dispatch:

jobs:
  handle-issue:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Docker
      uses: docker/setup-buildx-action@v3
      
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}
      
    - name: Create Claude credentials file
      run: |
        mkdir -p $HOME/.claude
        echo '${{ secrets.CLAUDE_CREDENTIALS_BASE64 }}' | base64 -d > $HOME/.claude/.credentials.json
        chmod 600 $HOME/.claude/.credentials.json
        
    - name: Run Claude Code Agent
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        REPO_URL: ${{ github.server_url }}/${{ github.repository }}
        PROMPT: "--detail"
        TASK_TYPE: "issue"
      run: |
        docker run --rm \
          -e GH_TOKEN \
          -e REPO_URL="$REPO_URL" \
          -e PROMPT="$PROMPT" \
          -e TASK_TYPE="$TASK_TYPE" \
          -v "$HOME/.claude/.credentials.json":/home/node/.claude/.credentials.json:rw \
          ghcr.io/dpeuscher/claude-code-agent:latest
