name: Claude – Token Refresh

# SCHEDULE DISABLED - Only manual trigger available
# on:
#   schedule:
#     - cron: '0 */4 * * *'  # Every 4 hours
on:
  workflow_dispatch:

jobs:
  refresh-token:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Refresh Claude Token & update repository secret
        env:
          GH_TOKEN: ${{ secrets.PAT_WRITE_SECRETS }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          CLAUDE_CREDENTIALS_B64: ${{ secrets.CLAUDE_CREDENTIALS_B64 }}
        run: |
          docker run --rm \
            -e GH_TOKEN \
            -e GITHUB_REPOSITORY \
            -e CLAUDE_CREDENTIALS_B64 \
            --entrypoint /usr/local/bin/token-refresh-entrypoint.sh \
            ghcr.io/dpeuscher/claude-code-agent:latest
