name: Debug – Echo Credentials (TEST ONLY)

on:
  workflow_dispatch:

jobs:
  debug-credentials:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Claude Credentials
        env:
          CLAUDE_CREDENTIALS_B64: ${{ secrets.CLAUDE_CREDENTIALS_B64 }}
        run: |
          echo "CLAUDE_CREDENTIALS_B64 content:"
          echo "$CLAUDE_CREDENTIALS_B64"
          echo ""
          echo "Length: ${#CLAUDE_CREDENTIALS_B64}"
          echo "First 50 chars: ${CLAUDE_CREDENTIALS_B64:0:50}..."
