name: Debug – Echo Credentials (TEST ONLY)

on:
  workflow_dispatch:

jobs:
  debug-credentials:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Claude Credentials Part 1 (1-180)
        env:
          CLAUDE_CREDENTIALS_B64: ${{ secrets.CLAUDE_CREDENTIALS_B64 }}
        run: |
          echo "CLAUDE_CREDENTIALS_B64 Part 1 (characters 1-180):"
          echo "${CLAUDE_CREDENTIALS_B64:0:180}"
          echo ""
          echo "Total length: ${#CLAUDE_CREDENTIALS_B64}"
      
      - name: Echo Claude Credentials Part 2 (180-370)
        env:
          CLAUDE_CREDENTIALS_B64: ${{ secrets.CLAUDE_CREDENTIALS_B64 }}
        run: |
          echo "CLAUDE_CREDENTIALS_B64 Part 2 (characters 180-370):"
          echo "${CLAUDE_CREDENTIALS_B64:180:190}"
          echo ""
          echo "Remaining length: $((${#CLAUDE_CREDENTIALS_B64} - 370))"
